version: "3"
services:
  hwsi:
    image: registry.cn-qingdao.aliyuncs.com/akvicors_images/hwsi:1.0
    container_name: hwsi
    restart: always
    volumes:
      - ./work:/go/src/github.com/AkvicorEdwards/hwsi/work
      - ./config:/go/src/github.com/AkvicorEdwards/hwsi/config/config
      - ./theme:/go/src/github.com/AkvicorEdwards/hwsi/theme
    ports:
      - 8080:80
